export const WEB3_INITIALIZED = 'WEB3_INITIALIZED';
export const WEB3_INITIALIZED_ERROR = 'WEB3_INTIALIZED_ERROR';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const CONTRACT_INITIALIZED = 'CONTRACT_INITIALIZED';

